general:
  path_to_val_csv: 'data/validation.csv'

llm:
  ANTHROPIC_API_KEY: ""
  OPENAI_API_KEY: ""
  GROQ_API_KEY: ""

embeddings_classifier:
  COHERE_API_KEY: ""
  cohere_embeddings_model: embed-multilingual-v3.0